-- QUESTOES 1 E 2
CREATE TABLE AUTOMOVEL (
placa CHAR (7),
marca VARCHAR (20),
modelo VARCHAR (20),
numero_serial CHAR (17)
);

CREATE TABLE SEGURADO (
cpf CHAR (11),
nome VARCHAR (30),
nascimento DATE,
endereco VARCHAR (30),
telefone VARCHAR (11)
);

CREATE TABLE PERITO (
cpf CHAR (11),
nome VARCHAR (30),
nascimento DATE,
endereco VARCHAR (30),
telefone VARCHAR (11),
data_contratacao DATE,
salario NUMERIC
);

CREATE TABLE OFICINA (
cnpj CHAR (11),
endereco VARCHAR (30),
nome VARCHAR(20),
telefone VARCHAR (11)
);

CREATE TABLE SEGURO (
id SERIAL,
cpf_segurado CHAR (11),
placa_automovel CHAR (7),
data_contratacao DATE,
validade DATE,
valor NUMERIC
);

CREATE TABLE SINISTRO (
id SERIAL,
horario_da_ocorrencia TIMESTAMP,
descricao VARCHAR (100),
num_seguro SERIAL
);

CREATE TABLE PERICIA (
id SERIAL,
cpf_perito CHAR(11),
num_sinistro SERIAL,
descricao VARCHAR (100)
);

CREATE TABLE REPARO (
id SERIAL,
num_pericia SERIAL,
valor NUMERIC,
cnpj_oficina CHAR (11)
);

-- QUESTAO 3
ALTER TABLE AUTOMOVEL ADD PRIMARY KEY placa;
ALTER TABLE SEGURADO ADD PRIMARY KEY cpf;
ALTER TABLE PERITO ADD PRIMARY KEY cpf;
ALTER TABLE OFICINA ADD PRIMARY KEY cnpj;
ALTER TABLE SEGURO ADD PRIMARY KEY id;
ALTER TABLE SINISTRO ADD PRIMARY KEY id;
ALTER TABLE PERICIA ADD PRIMARY KEY id;
ALTER TABLE REPARO ADD PRIMARY KEY id;

-- QUESTAO 4
ALTER TABLE SEGURO ADD CONSTRAINT chave_estrangeira FOREIGN KEY cpf_segurado REFERENCES SEGURADO cpf;
ALTER TABLE SEGURO ADD CONSTRAINT chave_estrangeira FOREIGN KEY placa_automovel REFERENCES AUTOMOVEL placa;
ALTER TABLE SINISTRO ADD CONSTRAINT chave_estrangeira FOREIGN KEY num_seguro REFERENCES SEGURO id;
ALTER TABLE PERICIA ADD CONSTRAINT chave_estrangeira FOREIGN KEY cpf_perito REFERENCES PERITO cpf;
ALTER TABLE PERICIA ADD CONSTRAINT chave_estrangeira FOREIGN KEY num_sinistro REFERENCES SINISTRO id;
ALTER TABLE REPARO ADD CONSTRAINT chave_estrangeira FOREIGN KEY num_pericia REFERENCES PERICIA id;
ALTER TABLE REPARO ADD CONSTRAINT chave_estrangeira FOREIGN KEY cnpj_oficina REFERENCES OFICINA cnpj;